### ISSUE TITLE
Ubuntu14.04でapt-get install ros-indigo-euslispが成功しない件

### ISSUE THREAD

**Issue by pcho0712** [agent-system/homework20150415#13]
表題のとおりです。
コンソール出力を末尾にコピペしておきます。

homework20150415を12.10 or aboveの手順にしたがってROSインストールをしましたが、おそらくディストリビューションの違いに起因すると思われるエラーが出ていて先に進めません。

なお、今年度配布された貸与PCはUbunts14.04がインストールされており、12系列ではありません。
対処法を教えていただければ幸いです。
# システム情報所属48-156329 

meip-users@UoT-IST-PC:~/ドキュメント/M1S/33_AgentSystem$ sudo apt-get install ros-indigo-euslisp
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています  
状態情報を読み取っています... 完了
インストールすることができないパッケージがありました。おそらく、あり得
ない状況を要求したか、(不安定版ディストリビューションを使用しているの
であれば) 必要なパッケージがまだ作成されていなかったり Incoming から移
動されていないことが考えられます。
以下の情報がこの問題を解決するために役立つかもしれません:

以下のパッケージには満たせない依存関係があります:
 ros-indigo-euslisp : 依存: xfonts-100dpi しかし、インストールすることができません
                      依存: xfonts-75dpi しかし、インストールすることができません
E: 問題を解決することができません。壊れた変更禁止パッケージがあります。
meip-users@UoT-IST-PC:~/ドキュメント/M1S/33_AgentSystem$ 
meip-users@UoT-IST-PC:~/ドキュメント/M1S/33_AgentSystem$ 
meip-users@UoT-IST-PC:~/ドキュメント/M1S/33_AgentSystem$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

**Comment by furushchev** [comment]
https://github.com/agent-system/homework20150415/pull/19
で対応しました。ありがとうございました。

**Comment by furushchev** [comment]
@pcho0712 #19 で解決したかどうか確認して、もし解決していたらこのissueをcloseしてくれると嬉しいです。
