### ISSUE TITLE
ubuntu14.04の場合/opt/ros/indigo/の下にsetup.bashのファイルが見つからない

### ISSUE THREAD

**Issue by yuataka** [agent-system/homework20150415#14]
ubuntu14.04の場合/opt/ros/indigo/の下にsetup.bashのファイルが見つかりません。

source ~/.bashrc　と入力すると下記のようなエラーメッセージが出ます。
bash: /opt/ros/indigo/setup.bash: そのようなファイルやディレクトリはありません

実際にlsで /opt/ros/indigo/を確認するとsetup.bashというファイルが存在していないことを確認しました。

**Comment by aginika** [comment]
issueありがとうございます。

```
sudo apt-get install ros-indigo-euslisp
```

をもう一度やっていただけますか？
エラーが出た場合、どんなエラーがでたかを貼っていただけると幸いです。

**Comment by ikeyan** [comment]
私も同じ問題に引っかかりました。

```
sudo apt-get install ros-indigo-euslisp
```

の結果は

```
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
ros-indigo-euslisp は既に最新バージョンです。
アップグレード: 0 個、新規インストール: 0 個、削除: 0 個、保留: 0 個。
```

です。
setup.bashを導入するパッケージはros-indigo-catkinのようです。
これに依存するパッケージは
- ros-indigo-ros
- ros-indigo-ros-core

などです。
私はとりあえず ros-indigo-ros-base を入れました。

**Comment by furushchev** [comment]
https://github.com/agent-system/homework20150415/pull/19 で対応しました。

**Comment by yuataka** [comment]
ros-indigo-ros-base を入れることで解決しました。ありがとうございます。
