### ISSUE TITLE
Ubuntu 14.04で irteusgl がインストールされない

### ISSUE THREAD

**Issue by ikeyan** [agent-system/homework20150415#18]
タイトルのとおりです。
エラーの文は

```
$ rosrun euslisp irteusgl
[rosrun] Couldn't find executable named irteusgl below /opt/ros/indigo/share/euslisp
```

です。
自己解決したので、私の解決法を共有します。よろしくお願いします。
- for Ubuntu 12.04に倣って ros-indigo-jskeus をインストールした。

```
  $ sudo apt-get install ros-indigo-jskeus
```
- デフォルトでインストールされていないフォントを使おうとして動かなかった。

```
X Error of failed request: BadFont (invalid Font parameter)
```

https://groups.google.com/forum/#!msg/rtm-ros-robotics/Vpy7wbha3Zg/gggLWW_BnswJ を参考に

```
$ sudo apt-get install xfonts-100dpi xfonts-75dpi msttcorefonts
```
- 再起動した。

```
sudo reboot
```
- irteusglがうまく立ち上がった。

**Comment by furushchev** [comment]
https://github.com/agent-system/homework20150415/pull/19 で対応しました。

**Comment by furushchev** [comment]
@ikeyan #19 で解決したかどうか確認して、もし解決していたらこのissueをcloseしてくれると嬉しいです。
