### ISSUE TITLE
Ubuntu12.04でrosrun euslisp irteusglが正しく実行されない

### ISSUE THREAD

**Issue by ghost** [agent-system/homework20150415#22]
rosrun euslisp irteusglを実行し、コマンドを入力しても、
IRTViewerが起動しませんでした。
Ubuntu12.04を使用し、
その手順に従ってROS / Euslispのセットアップを行いました。

rosrun euslisp irteusglの実行時と、
(load "irteus/demo/demo.l")の入力までのコンソールの
出力を添付します。

解決策を教えていただければ幸いです。

■　rosrun euslisp irteusgl 実行時の出力:
configuring by "/opt/ros/hydro/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble BINLOAD cannot dlopen: /opt/ros/hydro/share/euslisp/jskeus/eus/Linux/lib/libirteus.so: undefined symbol: tred2
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux/bin/irteusgl: ERROR th=0  0xc10e9b4 in (load-library (format nil "~A~A/lib/libirteus" _eusdir_ (unix:getenv "ARCHDIR")) '("irtmath" "irtutil" "irtc" "irtgeoc" "irtgraph" "pgsql"))E:

■　(load "irteus/demo/demo.l")入力時の出力
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux/bin/irteusgl: ERROR th=0 unbound variable robot-modelrobot-model in (make-class 'sample-robot :super robot-model :slots '(jc0 jc1 jh0 jh1 jal0 jal1 jal2 jal3 jal4 jal5 jal6 jar0 jar1 jar2 jar3 jar4 jar5 jar6 jll0 jll1 jll2 jll3 jll4 jll5 jlr0 jlr1 jlr2 jlr3 jlr4 jlr5) :metaclass nil :element-type nil :size -1 :documentation nil)E:

**Comment by k-okada** [comment]
that's is known bug only for 32bit machine, with jskeus < 1.0.4, please switch to shadow fixed.
https://github.com/euslisp/jskeus/issues/186

**Comment by furushchev** [comment]
32bitのubuntuで既知のバグが起こっていますが、aptの更新が間に合っていないようです。

https://github.com/agent-system/homework20150415/commit/4f9460f30b6f72b8328baabe2322028cf3ae347c
で対応しましたが、

``` bash
sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-get update
sudo apt-get install ros-hydro-roseus -f
```

としてもう一度試してみてください。

**Comment by ghost** [comment]
ご返信ありがとうございます．

shadow fixedも試してみましたが，やはり同様の問題が出てしまうようです．
(rosrun euslisp irteusgl 実行時に出力されるメッセージはほぼ同じでした．)

**Comment by ghost** [comment]
先程，
sudo apt-get upgrade
で新しいros-hydro-関連のパッケージがインストールされたので，
rosrun euslisp irteusgl
を実行し，コマンド：
(load "irteus/demo/demo.l")
を入力したところ，正しく動作しました．

対処していただき，ありがとうございました．
