### ISSUE TITLE
Ubuntu 14.04で rosrun euslisp irteusglが実行できない

### ISSUE THREAD

**Issue by YTakami** [agent-system/homework20150415#34]
直前ですみません。ほかの方のissue等を参考にしてもできなかったので、アドバイスをいただければと思います。

実行時の出力が以下になります。
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
can't load font "_-courier-medium-r-_-8-_"can't load font "_-courier-medium-r-_-10-_"can't load font "_-courier-medium-r-_-12-_"can't load font "_-courier-medium-r-_-14-_"can't load font "_-courier-medium-r-_-18-_"can't load font "_-courier-bold-r-_-12-_"can't load font "_-courier-bold-r-_-14-_"can't load font "_-courier-bold-r-_-18-_"can't load font "_-courier-bold-r-_-24-_"can't load font "_-times-medium-r-_-10-_"can't load font "_-times-medium-r-_-12-_"can't load font "_-times-bold-r-_-12-_"can't load font "_-times-bold-r-_-14-_"can't load font "_-times-bold-r-_-18-_"can't load font "_-times-bold-r-_-24-_"can't load font "lucidasans-bold-12"can't load font "lucidasans-bold-14"can't load font "_-Helvetica-Bold-R-Normal-_-12-_"can't load font "_-Helvetica-Medium-R-Normal-_-12-*"X Error of failed request:  BadFont (invalid Font parameter)
  Major opcode of failed request:  56 (X_ChangeGC)
  Resource id in failed request:  0x0
  Serial number of failed request:  49
  Current serial number in output stream:  58

https://groups.google.com/forum/#!msg/rtm-ros-robotics/Vpy7wbha3Zg/gggLWW_BnswJと同じ問題だったようなので、手順通りに進めたのですが、上記と同じエラーが返ってきます。
どうぞよろしくお願いいたします。

**Comment by furushchev** [comment]
返信が遅れました。
PCを再起動して再起動してもう一度実行してみてください。

**Comment by YTakami** [comment]
すみません、OSごと入れ替えることで何とか対処しました。一応再起動も試したのですが、結果は変わりませんでした。
根本的解決になっていないのですが、とりあえずこれで進めてみようと思います。
助言のほど本当にありがとうございました。
